export const GET_API_FOOD = 'API_FOOD';
export const FETCH_API_FOODS = 'FETCH_API_FOODS';
export const FETCH_API_CATEGORIES = 'FETCH_API_CATEGORIES';
export const FETCH_API_DRINKS = 'FETCH_API_DRINKS';
export const GET_CATEGORY = 'GET_CATEGORY';
export const ERROR_REQUEST_API_FOODS = 'ERROR_REQUEST_API_FOODS';
export const ERROR_REQUEST_API_DRINKS = 'ERROR_REQUEST_API_DRINKS';
export const GET_API_DRINKS = 'GET_API_DRINKS';
