export const RECIPE_FETCH = 'RECIPE_FETCH';
export const RECIPE_FETCH_SUCCESS_DATA = 'RECIPE_FETCH_SUCCESS_DATA';
export const RECIPE_FETCH_SUCCESS = 'RECIPE_FETCH_SUCCESS';
export const RECIPE_FETCH_ERROR = 'RECIPE_FETCH_ERROR';

export const RECIPE_DETAILS_FETCH = 'RECIPE_DETAILS_FETCH';
export const RECIPE_DETAILS_FETCH_SUCCESS_DATA = 'RECIPE_DETAILS_FETCH_SUCCESS_DATA';
export const RECIPE_DETAILS_FETCH_SUCCESS = 'RECIPE_DETAILS_FETCH_SUCCESS';
export const RECIPE_DETAILS_FETCH_ERROR = 'RECIPE_DETAILS_FETCH_ERROR';

export const RECIPE_EXPLORE_FETCH = 'RECIPE_EXPLORE_FETCH';
export const RECIPE_EXPLORE_FETCH_SUCCESS_DATA = 'RECIPE_EXPLORE_FETCH_SUCCESS_DATA';
export const RECIPE_EXPLORE_FETCH_SUCCESS = 'RECIPE_EXPLORE_FETCH_SUCCESS';
export const RECIPE_EXPLORE_FETCH_ERROR = 'RECIPE_EXPLORE_FETCH_ERROR';
