export const RECIPE_FETCH = 'RECIPE_FETCH';
export const RECIPE_FETCH_SUCCESS_DATA = 'RECIPE_FETCH_SUCCESS_DATA';
export const RECIPE_FETCH_SUCCESS = 'RECIPE_FETCH_SUCCESS';
export const RECIPE_FETCH_ERROR = 'RECIPE_FETCH_ERROR';

export const RECIPE_DETAILS_FETCH = 'RECIPE_DETAILS_FETCH';
export const RECIPE_DETAILS_FETCH_SUCCESS_DATA = 'RECIPE_DETAILS_FETCH_SUCCESS_DATA';
export const RECIPE_DETAILS_FETCH_SUCCESS = 'RECIPE_DETAILS_FETCH_SUCCESS';
export const RECIPE_DETAILS_FETCH_ERROR = 'RECIPE_DETAILS_FETCH_ERROR';

export const RECIPE_EXPLORE_FETCH = 'RECIPE_EXPLORE_FETCH';
export const RECIPE_EXPLORE_FETCH_SUCCESS_DATA = 'RECIPE_EXPLORE_FETCH_SUCCESS_DATA';
export const RECIPE_EXPLORE_FETCH_SUCCESS = 'RECIPE_EXPLORE_FETCH_SUCCESS';
export const RECIPE_EXPLORE_FETCH_ERROR = 'RECIPE_EXPLORE_FETCH_ERROR';

export const RECIPE_EXPLORE_REGIONS_FETCH = 'RECIPE_EXPLORE_FETCH';
export const
  RECIPE_EXPLORE_REGIONS_FETCH_SUCCESS_DATA = 'RECIPE_EXPLORE_FETCH_SUCCESS_DATA';
export const RECIPE_EXPLORE_REGIONS_FETCH_SUCCESS = 'RECIPE_EXPLORE_FETCH_SUCCESS';
export const RECIPE_EXPLORE_REGIONS_FETCH_ERROR = 'RECIPE_EXPLORE_FETCH_ERROR';

export const RECIPES_BY_REGIONS_FETCH = 'RECIPES_BY_REGIONS_FETCH';
export const
  RECIPES_BY_REGIONS_FETCH_SUCCESS_DATA = 'RECIPES_BY_REGIONS_FETCH_SUCCESS_DATA';
export const RECIPES_BY_REGIONS_FETCH_SUCCESS = 'RECIPES_BY_REGIONS_FETCH_SUCCESS';
export const RECIPES_BY_REGIONS_FETCH_ERROR = 'RECIPES_BY_REGIONS_FETCH_ERROR';

export const INGREDIENTS_FETCH = 'INGREDIENTS_FETCH';
export const INGREDIENTS_FETCH_SUCCESS_DATA = 'INGREDIENTS_FETCH_SUCCESS_DATA';
export const INGREDIENTS_FETCH_SUCCESS = 'INGREDIENTS_FETCH_SUCCESS';
export const INGREDIENTS_FETCH_ERROR = 'INGREDIENTS_FETCH_ERROR';
