export const dryMartiniSingleRecipe = [
  {
    idDrink: '11005',
    strDrink: 'Dry Martini',
    strDrinkAlternate: null,
    strTags: 'IBA,Classic,Christmas,Alcoholic',
    strVideo: null,
    strCategory: 'Cocktail',
    strIBA: 'Unforgettables',
    strAlcoholic: 'Alcoholic',
    strGlass: 'Cocktail glass',
    strInstructions: 'Straight: Pour all ingredients into mixing glass with ice cubes',
    strInstructionsES: null,
    strInstructionsDE: null,
    strInstructionsFR: null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/6ck9yi1589574317.jpg',
    strIngredient1: 'Gin',
    strIngredient2: 'Dry Vermouth',
    strIngredient3: 'Olive',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 2/3 oz ',
    strMeasure2: '1/3 oz ',
    strMeasure3: '1 ',
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: 'https://www.thecocktaildb.com/drink/11005',
    strImageAttribution: 'TheCocktailDB.com',
    strCreativeCommonsConfirmed: 'Yes',
    dateModified: '2017-09-02 12:51:35',
  },
];

export const initialDrinkSearch = {

};
